

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PLUMAPPLICATION
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class PLUMEntities1 : DbContext
{
    public PLUMEntities1()
        : base("name=PLUMEntities1")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<ClientInfo> ClientInfoes { get; set; }

    public virtual DbSet<Farmer> Farmers { get; set; }

    public virtual DbSet<Location> Locations { get; set; }

    public virtual DbSet<Role> Roles { get; set; }

    public virtual DbSet<TypeOfProduce> TypeOfProduces { get; set; }

    public virtual DbSet<UserRole> UserRoles { get; set; }

    public virtual DbSet<User> Users { get; set; }

}

}

